---
- name: restart zookeeper
  sudo: yes
  service: name=zookeeper state=restarted enabled=yes

- name: restart mesos-master
  sudo: yes
  service: name=mesos-master state=restarted enabled=yes

- name: restart marathon
  sudo: yes
  service: name=marathon state=restarted enabled=yes

- name: disable mesos-slave
  sudo: yes
  service: name=mesos-slave state=stopped enabled=no