---
- name: Add apt-key
  sudo: yes
  apt_key: id=E56151BF 
           keyserver=keyserver.ubuntu.com
           state=present

- name: Add Mesosphere Repo
  sudo: yes
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' 
                  state=present

- name: Install Deb Packages
  sudo: yes
  apt: pkg={{item}} 
       state=present 
       update_cache=yes
  with_items:
    - mesos
    - docker.io

- name: Disable Zookeeper
  sudo: yes
  template: src=zookeeper.override.j2 dest=/etc/init/zookeeper.override owner=root group=root mode=0644

- name: Disable Mesos-Master
  sudo: yes
  template: src=mesos-master.override.j2 dest=/etc/init/mesos-master.override owner=root group=root mode=0644
  notify: restart mesos-slave
  
- name: Update /etc/mesos/zk
  sudo: yes
  template: src=zk.j2 dest=/etc/mesos/zk owner=root group=root mode=0644
  notify: restart mesos-slave
