---
- name: Add apt-key
  sudo: yes
  apt_key: id=E56151BF 
           keyserver=keyserver.ubuntu.com
           state=present

- name: Add Mesosphere Repo
  sudo: yes
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' 
                  state=present

- name: Install Deb Packages
  sudo: yes
  apt: pkg={{item}} 
       state=present 
       update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - mesos